language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-html coverage --whitelist src tests
